# Generated by Django 3.2.10 on 2022-01-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default='courses/default.jpg', upload_to='courses/%Y/%m/%d/'),
        ),
    ]
